Catalog of My Things: Load and Save Book Data
mrcbq/catalog-of-my-things pull request #61
Opened 2023-08-08 22:00 UTC by romans-adi

For this PR these changes were made:

- Added `save` and `load` methods to the `Label` class to manage label data.
- Implemented the `load_all_labels` method during app initialization to load label data from `labels.json`.
- Added the `save_all_labels` method, which is called during app exit to save label data to `labels.json`.
- Displayed the `color` of the `label` alongside each book's details in the book list.
- Enhanced the `Book` class constructor to include `author` and `genre` parameters and displayed them in the `book list`.
- Utilized specific methods to acquire `genre` and `author` (first and last name separately) information from user input.
- Integrated `save` and `load` methods in the `Book` class for efficient management of book data.
- Stored data for both `Label` instances and `Book` instances in `JSON` format, enabling loading from `books.json` and `labels.json`.

2023-08-08 23:15 UTC, mrcbq requested changes
## Hi @romans-adi   🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 But there are some things that you can kindly improve for your code but you are almost there!

<img src="https://media.giphy.com/media/5bd388mBOAd5pBriyn/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] Please review the attached comments.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

2023-08-08 23:15 UTC, mrcbq commented on lib/app.rb
> +    save_labels
This method is not defined, and throws an error in the exit of the app.
Kindly, Please fix it.

2023-08-08 23:37 UTC, lincoln1883 requested changes
Hi, @romans-adi 👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great Ruby syntax.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the screencast under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-08 23:38 UTC, lincoln1883 commented
file:///home/lincoln/Videos/Screencasts/Screencast%20from%2008-08-2023%2008:29:36%20PM.webm

2023-08-09 02:55 UTC, lincoln1883 approved these changes
# Status: APPROVED 🟢 

Hi @mrcbq, and @lincoln1883 ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-09 03:24 UTC, mrcbq commented on .rubocop.yml
Hi, it doesn't help much to change the local linter rules in this file, since the ones that count are the ones read by the server in GitHub actions from the mv linters configuration file.
With this in mind, we should keep the local file identical to the online mv file.

2023-08-09 03:24 UTC, mrcbq commented on Gemfile.lock
Hello, I'm not sure that we are actually using all these libraries listed here, I am aware of at least the parser and rubocop libraries, could it be that the others come from installations of past projects?
Do you think we keep this file as clean as possible? we could even just ignore it in the .gitignore.

2023-08-09 03:24 UTC, mrcbq commented on lib/item.rb
> +    genre.add_item(self)
Hi, I'm not sure that we won't break code from other parties by modifying this method of the Item class. Please, Could you give me context on why it was necessary to change it?

2023-08-09 03:32 UTC, mrcbq approved these changes

2023-08-09 03:32 UTC, lincoln1883 commented on lib/item.rb
> +    genre.add_item(self)
Hey, Marco while I understand your concerns,  I just spent three hours debugging code I didn't write. The changes made Can be fixed or reverted to your liking. Any linter config committed is a part of the online side if you see something you don't agree with please change it to suit your desire.

2023-08-09 03:52 UTC, mrcbq commented on lib/item.rb
> +    genre.add_item(self)
I understand that you spend time debugging code that you did not write, I accept the changes on my part, you just need to approve them since you are also a reviewer.
I was just wondering why, when I reverted that line of code, nothing happened, it seems to be harmless. I asked since I thought you had more context, that's all.

2023-08-09 04:03 UTC, lincoln1883 commented on lib/item.rb
> +    genre.add_item(self)
I did it as a team member, not just a code reviewer. 
The line of code that was changed and didn't affect anything was changed on the way to finding the cause of the bug I left it as is because all the other methods were written in a similar pattern.

2023-08-09 04:10 UTC, lincoln1883 commented on lib/item.rb
> +    genre.add_item(self)
I don't see the point of all this we have far achieved what most teams haven't done, which is  create a product fully functional from start to finish without having to hard code any JSON file.

2023-08-09 04:21 UTC, mrcbq commented on lib/item.rb
> +    genre.add_item(self)
No problem at all Lincoln, of my side everything was approved a few minutes later that I wrote these comments, and I left these comments only to remember to ask later. 
I just asked for some context and you already gave it to me, thanks for that ;)

2023-08-09 04:38 UTC, mrcbq commented on lib/genre.rb
>      return nil unless new_item.is_a?(Item)
I change this line in my original code, I will change this for no conflict when merging the branch.
return if new_item.genre

2023-08-09 04:44 UTC, lincoln1883 commented on lib/genre.rb
>      return nil unless new_item.is_a?(Item)
ok

2023-08-09 05:02 UTC, merged